# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7109576769a8faf6a1a91a366b2db0223e65df34408170b6fbb630dcdbf99a5de950ec8fe420d34fd9852efe973cdc81b779e8a2d58f9e89cbb3ed3fb5078d7e

test:
  secret_key_base: 243b59cd28da3dfa8a16237f3315399d5696d616c8300cd2e6aed69a021665c392201850a1885612d1264535554a5f0adb97f4cd333946020aedc74d29e25283

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
